### ISSUE TITLE
max-width on images messes up Google Maps style

### ISSUE THREAD

**Issue by niksy** [niksy/platno#4]
Create special case for that:

``` css
.gm-style img {
    max-width:none;
    vertical-align:baseline;
}
```
